### ISSUE TITLE
Any other files worth mentioning in evaluation workflow

### ISSUE THREAD

**Issue by kevindewalt** [prolego-team/pdd#18]
I referenced 2 files in the readme: https://github.com/prolego-team/pdd?tab=readme-ov-file#create-an-evaluation-workflow
eval.py and the Json file.

Can you do a PR if there are other major ones worth mentioning?

Not urgent.

**Comment by jmpounders** [comment]
Those the are the only two that are worth mentioning.

There are other "plumbing" components that track the LLM and write out the results, but they are not worth calling out explicitly. They are imported into eval.py, so anyone interested could easily trace them from there.
